# -*- coding: utf-8 -*-
"""AO3 Identify and Extract Key Psychological Markers Code 4/6/25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e3nE0gXuSu_V4HdVg7VPZYELeTeqzwe2
"""

!pip install vaderSentiment

import pandas as pd
import re
import string
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
from textblob import TextBlob
from transformers import pipeline
import matplotlib.pyplot as plt

# 🔹 Load NLTK resources
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('punkt_tab')

# 🔹 Load the Dataset
file_path = "LD Trauma Stress.csv"
df = pd.read_csv(file_path)

# 🔹 Print column names to identify relevant text column
print("Column Names:", df.columns)

# 🔹 Assume text data is in a column named 'text' (adjust as needed)
text_column = "selftext"
df = df[[text_column, "Manual Stress Level"]].dropna()

# 🔹 Text Preprocessing Function
def clean_text(text):
    text = text.lower()  # Convert to lowercase
    text = re.sub(r"\s+", " ", text)  # Remove extra spaces
    text = re.sub(r"<.*?>", "", text)  # Remove HTML tags
    text = re.sub(r"\d+", "", text)  # Remove numbers
    text = text.translate(str.maketrans("", "", string.punctuation))  # Remove punctuation
    return text

df["cleaned_text"] = df[text_column].apply(clean_text)

# 🔹 Tokenization, Stopword Removal, Lemmatization
lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words("english"))

def normalize_text(text):
    tokens = word_tokenize(text)  # Tokenize
    tokens = [word for word in tokens if word not in stop_words]  # Remove stopwords
    tokens = [lemmatizer.lemmatize(word) for word in tokens]  # Lemmatization
    return " ".join(tokens)

df["normalized_text"] = df["cleaned_text"].apply(normalize_text)

# 🔹 Sentiment Analysis with VADER
analyzer = SentimentIntensityAnalyzer()
df["vader_sentiment"] = df["normalized_text"].apply(lambda x: analyzer.polarity_scores(x)["compound"])

# 🔹 Sentiment Analysis with TextBlob
df["textblob_sentiment"] = df["normalized_text"].apply(lambda x: TextBlob(x).sentiment.polarity)

# 🔹 Deep Learning Sentiment Analysis (Hugging Face)
sentiment_model = pipeline("sentiment-analysis", model="distilbert-base-uncased-finetuned-sst-2-english", truncation=True)
# Explicitly specify the model and enable truncation

hf_results = sentiment_model(df["normalized_text"].tolist())
df["hf_sentiment"] = [result["score"] if result["label"] == "POSITIVE" else -result["score"] for result in hf_results]

# Coping Strategy
positive_coping = {"hope", "try", "cope", "handle", "processing", "manage"}
negative_coping = {"done", "alone", "can’t", "can't", "give up", "struggling"}


def coping_direction(text):
    words = set(text.split())
    pos = len(words.intersection(positive_coping))
    neg = len(words.intersection(negative_coping))
    if pos > neg:
        return "positive coping"
    elif neg > pos:
        return "negative coping"
    else:
        return "neutral"

df["coping_type"] = df["normalized_text"].apply(coping_direction)

# 🔹 Assign Coping, Depression, and Stress Scores
def classify_coping(score):
    if score > 0.5:
        return "High Coping"
    elif score > 0:
        return "Moderate Coping"
    else:
        return "Low Coping"

def classify_anxiety(score):
    if score > 0.5:
        return "High Anxiety"
    elif score > 0:
        return "Moderate Anxiety"
    else:
        return "Low Anxiety"

def classify_depression(score):
    if score < -0.5:
        return "High Depression"
    elif score < 0:
        return "Moderate Depression"
    else:
        return "Low Depression"

def classify_stress(score):
  if score > 0.5:
    return "High Stress"
  elif score > 0:
    return "Moderate Stress"
  else:
    return "Low Stress"

df["coping"] = df["vader_sentiment"].apply(classify_coping)
df["anxiety"] = df["vader_sentiment"].apply(classify_anxiety)
df["depression"] = df["vader_sentiment"].apply(classify_depression)
df["stress"] = df["vader_sentiment"].apply(classify_stress)

# Mental Health word sets
anxiety_words = {"anxious", "panic", "worried", "nervous", "fear", "stressed", "racing thoughts"}
depression_words = {"sad", "tired", "empty", "numb", "hopeless", "worthless", "exhausted", "disconnected"}
stress_words = {"overwhelmed", "tense", "pressure", "burned out", "frustrated", "irritable", "on edge", "stress", "stressed", "strained"}

# Keyword counting function
def count_keywords(text, word_set):
    return sum(1 for word in text.split() if word in word_set)

# Apply counts
df["anxiety_word_count"] = df["normalized_text"].apply(lambda x: count_keywords(x, anxiety_words))
df["depression_word_count"] = df["normalized_text"].apply(lambda x: count_keywords(x, depression_words))
df["stress_word_count"] = df["normalized_text"].apply(lambda x: count_keywords(x, stress_words))

# Hopelessness Dictionary
hopeless_words = {"hopeless", "worthless", "useless", "pointless", "meaningless", "empty", "nobody"}

def hopelessness_score(text):
    return sum(1 for word in text.split() if word in hopeless_words)

df["hopelessness_level"] = df["normalized_text"].apply(hopelessness_score)

def multi_label_mental_health(text):
    text = text.lower()
    labels = []
    if any(x in text for x in ["anxious", "panic", "worried", "nervous", "fear", "stressed", "racing thoughts"]):
        labels.append("anxiety")
    if any(x in text for x in ["sad", "tired", "empty", "numb", "hopeless", "worthless", "exhausted", "disconnected"]):
        labels.append("depression")
    if any(x in text for x in ["overwhelmed", "tense", "pressure", "burned out", "frustrated", "irritable", "on edge", "stress", "stressed", "strained"]):
        labels.append("stress")
    return ", ".join(labels) if labels else "unspecified"

df["mental_health_category"] = df["cleaned_text"].apply(multi_label_mental_health)

# Alert Phrases
alert_phrases = [
    "feeling overwhelmed", "constant anxiety", "can’t sleep", "numb", "panic attack",
    "burned out", "worthless", "no motivation", "everything is too much"
]

def flag_alert_phrases(text):
    flags = [phrase for phrase in alert_phrases if phrase in text]
    return "; ".join(flags) if flags else None

df["alert_flags"] = df["cleaned_text"].apply(flag_alert_phrases)

# 🔹 Save Results to CSV
output_path = "Mental_Health_Analysis_4.6.25.csv"
df.to_csv(output_path, index=False)
print(f"Results saved to {output_path}")

# Count each mental health category
category_counts = df["mental_health_category"].value_counts()

# Bar plot
plt.figure(figsize=(8, 6))
ax = category_counts.plot(kind="bar", color="teal", alpha=0.8)

# Add count labels on top of each bar
for i, value in enumerate(category_counts):
    ax.text(i, value + 0.5, str(value), ha='center', va='bottom', fontsize=10)

# Final plot formatting
plt.title("Distribution of Mental Health Categories")
plt.xlabel("Mental Health Condition")
plt.ylabel("Number of Posts")
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig("mental_health_category_distribution.png")
plt.show()

# Step 1: Drop missing values (if any)
alert_series = df["alert_flags"].dropna()

# Step 2: Split and explode multi-phrase rows (if you used "; " as a separator)
alert_exploded = alert_series.str.split("; ").explode().str.strip()

# Step 3: Count frequency of each alert phrase
alert_counts = alert_exploded.value_counts()

# Step 4: Plot
plt.figure(figsize=(10, 6))
ax = alert_counts.plot(kind='barh', color='crimson', alpha=0.85)
plt.title("Most Common High-Risk Alert Phrases")
plt.xlabel("Number of Posts")
plt.ylabel("Alert Phrase")

# Step 5: Add value labels on bars
for i, v in enumerate(alert_counts):
    ax.text(v + 0.5, i, str(v), color='black', va='center', fontsize=10)

plt.tight_layout()
plt.savefig("alert_flags_distribution.png")
plt.show()

#import WordCloud
from wordcloud import WordCloud

# 🔹 Generate a Word Cloud
all_text = " ".join(df["normalized_text"])

wordcloud = WordCloud(
    width=800, height=400, background_color="black", colormap="coolwarm",
    max_words=100, contour_color="white"
).generate(all_text)

# 🔹 Display the Word Cloud
plt.figure(figsize=(12, 6))
plt.imshow(wordcloud, interpolation="bilinear")
plt.axis("off")
plt.title("Word Cloud of Most Common Words", fontsize=14)
plt.show()